version: "3"

tasks:
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:
      - task: generate
  generate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - gen
    desc: "Generate code from proto files"
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc -I api/proto api/proto/*.proto --go_out=./api/gen --go_opt=paths=source_relative --go-grpc_out=./api/gen
